#!/usr/bin/env bash
# Pinned contract snapshot sync.
#
# Vendors the generated SDK type artefacts — openapi.yaml + the Go/TS type
# files — from a PINNED snapshot of the core Mashgate monorepo into this repo's
# sdk/*/_generated/ directories, then fails if the result drifts from what is
# committed.
#
# Source of truth lives in the mashgate monorepo, NOT here:
#   - proto contracts:  mashgate/contracts/proto/v1/*.proto
#   - codegen pipeline: mashgate `make sdk-gen-go` / `make sdk-gen-ts`
#                       (protoc + protoc-gen-openapi -> openapi.yaml ->
#                        oapi-codegen [Go] / openapi-typescript [TS])
# This script fetches the pinned snapshot, runs that codegen, copies the
# artefacts here, and diff-checks. The Python SDK is hand-written and is NOT
# regenerated by this script.
#
# Intended to run on the srv2 build host, which already has the toolchain
# (git, protoc, protoc-gen-openapi, oapi-codegen, openapi-typescript, go, node;
# yq optional). Pinning comes from contracts-sync/manifests/active.yaml.
#
# Usage:
#   ./contracts-sync/scripts/sync.sh                  # regen + show drift
#   CHECK_ONLY=1 ./contracts-sync/scripts/sync.sh     # verify no drift, leave tree clean (CI gate)
#   MASHGATE_SRC=/opt/mashgate ./contracts-sync/scripts/sync.sh   # reuse an existing checkout (recommended on srv2)
#
# Optional overrides if mashgate's codegen output locations are non-obvious:
#   GO_OPENAPI_OUT=... GO_TYPES_OUT=... TS_TYPES_OUT=...

set -euo pipefail

log() { printf '→ %s\n' "$*"; }
die() { printf 'sync.sh: %s\n' "$*" >&2; exit 1; }

# ── locate repo root + manifest (work from any cwd) ──────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MANIFEST="$REPO_ROOT/contracts-sync/manifests/active.yaml"
[[ -f "$MANIFEST" ]] || die "missing manifest: $MANIFEST"

# ── read a scalar from the manifest (yq when available, else a targeted grep) ─
manifest_get() {
  # $1 = bare key (e.g. head_ref); $2 = yq path (e.g. .snapshot.head_ref)
  local val
  if command -v yq >/dev/null 2>&1; then
    val="$(yq -r "$2 // \"\"" "$MANIFEST" 2>/dev/null || true)"
  fi
  if [[ -z "${val:-}" || "$val" == "null" ]]; then
    val="$(grep -E "^[[:space:]]*$1:" "$MANIFEST" | head -1 \
      | sed -E 's/^[^:]*:[[:space:]]*//; s/[[:space:]]*#.*$//; s/^"//; s/"$//; s/[[:space:]]*$//')"
  fi
  printf '%s' "$val"
}

SOURCE="$(manifest_get source '.snapshot.source')"            # github.com/saidmashhud/mashgate
HEAD_REF="$(manifest_get head_ref '.snapshot.head_ref')"      # exact origin/main SHA used last
TAG="$(manifest_get tag '.snapshot.tag')"                     # fallback: cut tag
REF="${HEAD_REF:-$TAG}"
[[ -n "$SOURCE" ]] || die "manifest has no snapshot.source"
[[ -n "$REF" ]]    || die "manifest has no snapshot.head_ref or .tag"
log "pinned snapshot: $SOURCE @ $REF"

# ── obtain a mashgate checkout at REF ────────────────────────────────────────
WORK=""
cleanup() { [[ -n "$WORK" && -d "$WORK" ]] && rm -rf "$WORK"; }
trap cleanup EXIT

if [[ -n "${MASHGATE_SRC:-}" ]]; then
  SRC="$MASHGATE_SRC"
  [[ -d "$SRC/.git" ]] || die "MASHGATE_SRC=$SRC is not a git checkout"
  log "using existing checkout $SRC (fetch + checkout $REF)"
  git -C "$SRC" fetch --quiet --all --tags || true
  git -C "$SRC" checkout --quiet "$REF" || die "ref $REF not found in $SRC"
else
  command -v git >/dev/null 2>&1 || die "git not found"
  WORK="$(mktemp -d)"
  SRC="$WORK/mashgate"
  log "cloning https://$SOURCE.git @ $REF (set MASHGATE_SRC=/opt/mashgate to reuse a checkout)"
  git clone --quiet "https://$SOURCE.git" "$SRC" || die "clone failed (private repo? provide MASHGATE_SRC instead)"
  git -C "$SRC" checkout --quiet "$REF" || die "ref $REF not found after clone"
fi

# ── run the mashgate-side codegen (the pipeline's source of truth) ───────────
command -v make >/dev/null 2>&1 || die "make not found"
log "running codegen: make -C $SRC sdk-gen-go sdk-gen-ts"
make -C "$SRC" sdk-gen-go sdk-gen-ts

# ── discover the freshly generated artefacts (paths are owned by mashgate) ───
find_newest() { # $1 = basename -> newest matching file under $SRC
  find "$SRC" -type f -name "$1" -not -path '*/node_modules/*' -not -path '*/.git/*' \
    -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-
}
GO_OPENAPI="${GO_OPENAPI_OUT:-$(find_newest openapi.yaml)}"
GO_TYPES="${GO_TYPES_OUT:-$(find_newest types.gen.go)}"
TS_TYPES="${TS_TYPES_OUT:-$(find_newest types.ts)}"
for pair in "GO_OPENAPI:$GO_OPENAPI" "GO_TYPES:$GO_TYPES" "TS_TYPES:$TS_TYPES"; do
  name="${pair%%:*}"; path="${pair#*:}"
  [[ -n "$path" && -f "$path" ]] || die "could not locate generated artefact for $name under $SRC (override with ${name}_OUT)"
  log "  $name = $path"
done

# ── vendor into this repo ────────────────────────────────────────────────────
GO_DST="$REPO_ROOT/sdk/go/_generated"
TS_DST="$REPO_ROOT/sdk/typescript/src/_generated"
[[ -d "$GO_DST" && -d "$TS_DST" ]] || die "destination _generated dirs missing"
cp "$GO_OPENAPI" "$GO_DST/openapi.yaml"
cp "$GO_TYPES"   "$GO_DST/types.gen.go"
cp "$TS_TYPES"   "$TS_DST/types.ts"
cp "$GO_OPENAPI" "$TS_DST/openapi.yaml"   # the same openapi feeds both generators
log "vendored artefacts into sdk/go/_generated and sdk/typescript/src/_generated"

# ── drift check ──────────────────────────────────────────────────────────────
GEN_PATHS=(sdk/go/_generated sdk/typescript/src/_generated)
if git -C "$REPO_ROOT" diff --quiet -- "${GEN_PATHS[@]}"; then
  log "✓ no drift — committed artefacts already match snapshot $REF"
  exit 0
fi

if [[ -n "${CHECK_ONLY:-}" ]]; then
  echo "✗ DRIFT: committed _generated artefacts differ from snapshot $REF" >&2
  git -C "$REPO_ROOT" --no-pager diff --stat -- "${GEN_PATHS[@]}" >&2
  git -C "$REPO_ROOT" checkout -- "${GEN_PATHS[@]}"   # leave the tree clean
  exit 1
fi

log "✓ regenerated — _generated updated; review + commit:"
git -C "$REPO_ROOT" --no-pager diff --stat -- "${GEN_PATHS[@]}"
