#!/usr/bin/env bash
# Pinned contract snapshot sync.
#
# Vendors the generated SDK type artefacts — openapi.yaml + the Go/TS type
# files — from a PINNED snapshot of the core Mashgate monorepo into this repo's
# sdk/*/_generated/ directories, then fails if the result drifts from what is
# committed.
#
# Source of truth lives in the mashgate monorepo, NOT here:
#   - proto contracts:  mashgate/contracts/proto/v1/*.proto
#   - codegen pipeline: mashgate `make sdk-gen-go` / `make sdk-gen-ts`
#                       (protoc + protoc-gen-openapi -> openapi.yaml ->
#                        oapi-codegen [Go] / openapi-typescript [TS])
# This script fetches the pinned snapshot, runs the same codegen pipeline, and
# diff-checks the generated artefacts. The Python SDK is hand-written and is NOT
# regenerated by this script.
#
# Intended to run on the srv2 build host, which already has the toolchain
# (git, protoc, protoc-gen-openapi, oapi-codegen, openapi-typescript, go, node;
# yq optional). Pinning comes from contracts-sync/manifests/active.yaml.
#
# Usage:
#   ./contracts-sync/scripts/sync.sh                  # regen + show drift
#   CHECK_ONLY=1 ./contracts-sync/scripts/sync.sh     # verify no drift, leave tree clean (CI gate)
#   MASHGATE_SRC=/opt/mashgate ./contracts-sync/scripts/sync.sh   # clone from an existing checkout (recommended on srv2)
#
set -euo pipefail

log() { printf '→ %s\n' "$*"; }
die() { printf 'sync.sh: %s\n' "$*" >&2; exit 1; }

# srv2 keeps codegen binaries here. Prepending is harmless on developer machines.
if [[ -d /opt/codegen ]]; then
  export PATH="/opt/codegen:$PATH"
fi

# ── locate repo root + manifest (work from any cwd) ──────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MANIFEST="$REPO_ROOT/contracts-sync/manifests/active.yaml"
[[ -f "$MANIFEST" ]] || die "missing manifest: $MANIFEST"

git_repo() {
  git -c "safe.directory=$REPO_ROOT" -C "$REPO_ROOT" "$@"
}

# ── read a scalar from the manifest (yq when available, else a targeted grep) ─
manifest_get() {
  # $1 = bare key (e.g. head_ref); $2 = yq path (e.g. .snapshot.head_ref)
  local val
  if command -v yq >/dev/null 2>&1; then
    val="$(yq -r "$2 // \"\"" "$MANIFEST" 2>/dev/null || true)"
  fi
  if [[ -z "${val:-}" || "$val" == "null" ]]; then
    val="$(grep -E "^[[:space:]]*$1:" "$MANIFEST" | head -1 \
      | sed -E 's/^[^:]*:[[:space:]]*//; s/[[:space:]]*#.*$//; s/^"//; s/"$//; s/[[:space:]]*$//')"
  fi
  printf '%s' "$val"
}

SOURCE="$(manifest_get source '.snapshot.source')"            # github.com/saidmashhud/mashgate
HEAD_REF="$(manifest_get head_ref '.snapshot.head_ref')"      # exact origin/main SHA used last
TAG="$(manifest_get tag '.snapshot.tag')"                     # fallback: cut tag
REF="${HEAD_REF:-$TAG}"
[[ -n "$SOURCE" ]] || die "manifest has no snapshot.source"
[[ -n "$REF" ]]    || die "manifest has no snapshot.head_ref or .tag"
log "pinned snapshot: $SOURCE @ $REF"

# ── obtain a mashgate checkout at REF ────────────────────────────────────────
WORK=""
CODEGEN_WORK=""
cleanup() {
  [[ -n "$WORK" && -d "$WORK" ]] && rm -rf "$WORK"
  [[ -n "$CODEGEN_WORK" && -d "$CODEGEN_WORK" ]] && rm -rf "$CODEGEN_WORK"
}
trap cleanup EXIT

if [[ -z "${MASHGATE_SRC:-}" && -d "$REPO_ROOT/../mashgate/.git" ]]; then
  MASHGATE_SRC="$REPO_ROOT/../mashgate"
fi

if [[ -n "${MASHGATE_SRC:-}" ]]; then
  SOURCE_CHECKOUT="$MASHGATE_SRC"
  git -C "$SOURCE_CHECKOUT" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
    || die "MASHGATE_SRC=$SOURCE_CHECKOUT is not a git checkout"
  log "using existing checkout $SOURCE_CHECKOUT as a read-only object source"
  git -C "$SOURCE_CHECKOUT" fetch --quiet --all --tags || true
  git -C "$SOURCE_CHECKOUT" cat-file -e "$REF^{commit}" 2>/dev/null \
    || die "ref $REF not found in $SOURCE_CHECKOUT"

  # Never checkout the pinned contracts ref in the operator's source tree.
  # A temporary shared clone reuses local Git objects while keeping the source
  # checkout's branch, index, and worktree untouched.
  WORK="$(mktemp -d)"
  SRC="$WORK/mashgate"
  git clone --quiet --shared --no-checkout "$SOURCE_CHECKOUT" "$SRC" \
    || die "failed to clone from MASHGATE_SRC=$SOURCE_CHECKOUT"
  git -C "$SRC" checkout --quiet --detach "$REF" \
    || die "ref $REF could not be checked out in the temporary clone"
else
  command -v git >/dev/null 2>&1 || die "git not found"
  WORK="$(mktemp -d)"
  SRC="$WORK/mashgate"
  log "cloning https://$SOURCE.git @ $REF (set MASHGATE_SRC=/opt/mashgate to reuse a checkout)"
  git clone --quiet "https://$SOURCE.git" "$SRC" || die "clone failed (private repo? provide MASHGATE_SRC instead)"
  git -C "$SRC" checkout --quiet "$REF" || die "ref $REF not found after clone"
fi

# ── run codegen from the pinned contracts ────────────────────────────────────
GO_DST="$REPO_ROOT/sdk/go/_generated"
TS_DST="$REPO_ROOT/sdk/typescript/src/_generated"
[[ -d "$GO_DST" && -d "$TS_DST" ]] || die "destination _generated dirs missing"

for tool in protoc protoc-gen-openapi oapi-codegen node npx; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool not found"
done

CODEGEN_WORK="$(mktemp -d)"
mkdir -p "$CODEGEN_WORK/out"

log "generating OpenAPI from $SRC/contracts/proto/v1/*.proto"
protoc --proto_path="$SRC/contracts/proto" \
  '--openapi_out=Mgoogle/api/http.proto=google.golang.org/genproto/googleapis/api/annotations,Mgoogle/api/annotations.proto=google.golang.org/genproto/googleapis/api/annotations:'"$CODEGEN_WORK/out" \
  "$SRC"/contracts/proto/v1/*.proto

log "deduplicating duplicate operationIds"
node "$SRC/scripts/sdk-dedup-openapi.mjs" "$CODEGEN_WORK/out/openapi.yaml"

log "generating Go models with oapi-codegen"
cat > "$CODEGEN_WORK/types.cfg.yaml" <<EOF
package: mashgatev1
generate:
  models: true
output: $CODEGEN_WORK/out/types.gen.go
EOF
oapi-codegen --config "$CODEGEN_WORK/types.cfg.yaml" "$CODEGEN_WORK/out/openapi.yaml"

log "generating TypeScript types with openapi-typescript"
(cd "$CODEGEN_WORK" && npx --yes openapi-typescript@7 out/openapi.yaml -o out/types.ts)

for path in \
  "$CODEGEN_WORK/out/openapi.yaml" \
  "$CODEGEN_WORK/out/types.gen.go" \
  "$CODEGEN_WORK/out/types.ts"
do
  [[ -s "$path" ]] || die "generated artefact missing or empty: $path"
done

GENERATED_SOURCES=(
  "$CODEGEN_WORK/out/openapi.yaml"
  "$CODEGEN_WORK/out/types.gen.go"
  "$CODEGEN_WORK/out/openapi.yaml"
  "$CODEGEN_WORK/out/types.ts"
)
GENERATED_DESTINATIONS=(
  "$GO_DST/openapi.yaml"
  "$GO_DST/types.gen.go"
  "$TS_DST/openapi.yaml"
  "$TS_DST/types.ts"
)

# Compare generated bytes directly so CHECK_ONLY also works from a source
# archive that does not contain .git metadata.
DRIFT=0
for index in "${!GENERATED_SOURCES[@]}"; do
  if ! cmp -s "${GENERATED_SOURCES[$index]}" "${GENERATED_DESTINATIONS[$index]}"; then
    DRIFT=1
  fi
done

if [[ "$DRIFT" == "0" ]]; then
  log "✓ no drift — committed artefacts already match snapshot $REF"
  exit 0
fi

if [[ -n "${CHECK_ONLY:-}" ]]; then
  echo "✗ DRIFT: committed _generated artefacts differ from snapshot $REF" >&2
  for index in "${!GENERATED_SOURCES[@]}"; do
    if ! cmp -s "${GENERATED_SOURCES[$index]}" "${GENERATED_DESTINATIONS[$index]}"; then
      printf '  changed: %s\n' "${GENERATED_DESTINATIONS[$index]#$REPO_ROOT/}" >&2
    fi
  done
  exit 1
fi

for index in "${!GENERATED_SOURCES[@]}"; do
  cp "${GENERATED_SOURCES[$index]}" "${GENERATED_DESTINATIONS[$index]}"
done
log "generated artefacts updated in sdk/go/_generated and sdk/typescript/src/_generated"

log "✓ regenerated — _generated updated; review + commit:"
if git_repo rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_repo --no-pager diff HEAD --stat -- sdk/go/_generated sdk/typescript/src/_generated
else
  printf '  sdk/go/_generated\n  sdk/typescript/src/_generated\n'
fi
