package mashgate

import (
	"context"
	"encoding/json"
	"net/http"
	"testing"
)

func TestCreateCheckout_success(t *testing.T) {
	want := CheckoutSession{
		SessionID:   "cs_xyz789",
		Status:      "pending",
		CheckoutURL: "https://pay.mashgate.uz/cs_xyz789",
		TotalAmount: Money{Amount: "2500000.00", Currency: "UZS"},
		SuccessURL:  "https://zist.uz/success",
		CancelURL:   "https://zist.uz/cancel",
	}

	_, client := newTestServer(t, http.StatusCreated, map[string]any{
		"session":     want,
		"checkoutUrl": want.CheckoutURL,
	})

	got, err := client.CreateCheckout(context.Background(), CreateCheckoutRequest{
		TotalAmount:   Money{Amount: "2500000.00", Currency: "UZS"},
		SuccessURL:    "https://zist.uz/success",
		CancelURL:     "https://zist.uz/cancel",
		CustomerEmail: "guest@example.com",
		Items: []LineItem{
			{
				Name:      "Apartment in Tashkent",
				Quantity:  3,
				UnitPrice: Money{Amount: "833333.33", Currency: "UZS"},
			},
		},
	})
	if err != nil {
		t.Fatalf("CreateCheckout error: %v", err)
	}
	if got.SessionID != want.SessionID {
		t.Errorf("expected SessionID %q, got %q", want.SessionID, got.SessionID)
	}
	if got.CheckoutURL != want.CheckoutURL {
		t.Errorf("expected CheckoutURL %q, got %q", want.CheckoutURL, got.CheckoutURL)
	}
}

func TestCreateCheckout_idempotencyAutoGenerated(t *testing.T) {
	var capturedKey string

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		capturedKey = r.Header.Get("Idempotency-Key")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"session": CheckoutSession{SessionID: "cs_auto"},
		})
	})

	_, err := client.CreateCheckout(context.Background(), CreateCheckoutRequest{
		TotalAmount: Money{Amount: "100000.00", Currency: "UZS"},
		SuccessURL:  "https://zist.uz/success",
		CancelURL:   "https://zist.uz/cancel",
	})
	if err != nil {
		t.Fatalf("CreateCheckout error: %v", err)
	}
	if capturedKey == "" {
		t.Fatal("expected Idempotency-Key header to be set, got empty string")
	}
}

func TestCompleteCheckout_wallet(t *testing.T) {
	wantRedirect := "https://my.click.uz/pay?txn=12345"

	var capturedBody map[string]any

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewDecoder(r.Body).Decode(&capturedBody)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(CompleteCheckoutResponse{
			Success:           true,
			PaymentID:         "pay_wallet_123",
			WalletRedirectURL: wantRedirect,
		})
	})

	got, err := client.CompleteCheckout(context.Background(), "cs_xyz789", CompleteCheckoutRequest{
		PaymentMethodType: "wallet",
		Wallet: &WalletPaymentMethod{
			Provider: "click",
			Phone:    "+998901234567",
		},
	})
	if err != nil {
		t.Fatalf("CompleteCheckout error: %v", err)
	}
	if !got.Success {
		t.Error("expected Success=true")
	}
	if got.WalletRedirectURL != wantRedirect {
		t.Errorf("expected WalletRedirectURL %q, got %q", wantRedirect, got.WalletRedirectURL)
	}

	// Verify the request body contained the wallet provider
	if wallet, ok := capturedBody["wallet"].(map[string]any); !ok {
		t.Error("expected wallet field in request body")
	} else if wallet["provider"] != "click" {
		t.Errorf("expected provider=click, got %v", wallet["provider"])
	}
}

func TestExpireCheckout_success(t *testing.T) {
	_, client := newTestServer(t, http.StatusOK, map[string]bool{"success": true})

	err := client.ExpireCheckout(context.Background(), "cs_expired")
	if err != nil {
		t.Fatalf("ExpireCheckout error: %v", err)
	}
}

func TestGetCheckout_notFound(t *testing.T) {
	_, client := newTestServer(t, http.StatusNotFound, map[string]string{
		"message": "session not found",
	})

	_, err := client.GetCheckout(context.Background(), "cs_does_not_exist")

	var nfe *NotFoundError
	if !isErrorType(err, &nfe) {
		t.Fatalf("expected *NotFoundError, got: %T %v", err, err)
	}
}

func TestCreateCheckout_validation(t *testing.T) {
	_, client := newTestServer(t, http.StatusUnprocessableEntity, map[string]string{
		"field":   "successUrl",
		"message": "successUrl is required",
	})

	_, err := client.CreateCheckout(context.Background(), CreateCheckoutRequest{
		TotalAmount: Money{Amount: "100.00", Currency: "UZS"},
		// SuccessURL intentionally missing
		CancelURL: "https://zist.uz/cancel",
	})

	var ve *ValidationError
	if !isErrorType(err, &ve) {
		t.Fatalf("expected *ValidationError, got: %T %v", err, err)
	}
	if ve.Field != "successUrl" {
		t.Errorf("expected Field=successUrl, got %q", ve.Field)
	}
}
