package mashgate

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

// newTestServer creates an httptest.Server that responds with the given status
// and JSON body for any request. Returns the server and a client pointed at it.
func newTestServer(t *testing.T, status int, body any) (*httptest.Server, *Client) {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
		if body != nil {
			_ = json.NewEncoder(w).Encode(body)
		}
	}))
	t.Cleanup(srv.Close)
	return srv, New(srv.URL, "mg_test_key")
}

// newTestServerFn creates a server with a custom handler function.
func newTestServerFn(t *testing.T, fn http.HandlerFunc) (*httptest.Server, *Client) {
	t.Helper()
	srv := httptest.NewServer(fn)
	t.Cleanup(srv.Close)
	return srv, New(srv.URL, "mg_test_key")
}

func TestCreatePayment_success(t *testing.T) {
	want := Payment{
		PaymentID: "pay_abc123",
		Status:    "pending",
		Amount:    Money{Amount: "150000.00", Currency: "UZS"},
		OrderID:   "order_001",
	}

	_, client := newTestServer(t, http.StatusCreated, want)

	got, err := client.CreatePayment(context.Background(), CreatePaymentRequest{
		Amount:  Money{Amount: "150000.00", Currency: "UZS"},
		OrderID: "order_001",
	})
	if err != nil {
		t.Fatalf("CreatePayment returned error: %v", err)
	}
	if got.PaymentID != want.PaymentID {
		t.Errorf("got PaymentID %q, want %q", got.PaymentID, want.PaymentID)
	}
	if got.Status != want.Status {
		t.Errorf("got Status %q, want %q", got.Status, want.Status)
	}
}

func TestClientUsesAPIKeyHeader(t *testing.T) {
	var apiKey string
	var authorization string

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		apiKey = r.Header.Get("X-API-Key")
		authorization = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(Payment{PaymentID: "pay_header", Status: "pending"})
	})

	_, err := client.CreatePayment(context.Background(), CreatePaymentRequest{
		Amount:  Money{Amount: "150000.00", Currency: "UZS"},
		OrderID: "order_header",
	})
	if err != nil {
		t.Fatalf("CreatePayment returned error: %v", err)
	}
	if apiKey != "mg_test_key" {
		t.Fatalf("expected X-API-Key mg_test_key, got %q", apiKey)
	}
	if authorization != "" {
		t.Fatalf("expected no Authorization header for API key auth, got %q", authorization)
	}
}

func TestCreatePayment_unauthorized(t *testing.T) {
	_, client := newTestServer(t, http.StatusUnauthorized, map[string]string{
		"message": "invalid api key",
	})

	_, err := client.CreatePayment(context.Background(), CreatePaymentRequest{
		Amount:  Money{Amount: "100.00", Currency: "UZS"},
		OrderID: "order_002",
	})

	apiErr, ok := err.(*Error)
	if !ok {
		t.Fatalf("expected *Error, got: %T %v", err, err)
	}
	if apiErr.Code != "unauthorized" || apiErr.StatusCode != http.StatusUnauthorized {
		t.Fatalf("unexpected error: %#v", apiErr)
	}
}

func TestGetPayment_notFound(t *testing.T) {
	_, client := newTestServer(t, http.StatusNotFound, map[string]string{
		"message": "payment not found",
	})

	_, err := client.GetPayment(context.Background(), "pay_does_not_exist")

	apiErr, ok := err.(*Error)
	if !ok {
		t.Fatalf("expected *Error, got: %T %v", err, err)
	}
	if apiErr.Code != "not_found" || apiErr.StatusCode != http.StatusNotFound {
		t.Fatalf("unexpected error: %#v", apiErr)
	}
}

func TestRefundPayment_success(t *testing.T) {
	var capturedBody map[string]any

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		_ = json.NewDecoder(r.Body).Decode(&capturedBody)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(Payment{
			PaymentID: "pay_refunded",
			Status:    "refunded",
			Amount:    Money{Amount: "50000.00", Currency: "UZS"},
		})
	})

	got, err := client.RefundPayment(context.Background(), "pay_refunded", RefundRequest{
		Amount: Money{Amount: "50000.00", Currency: "UZS"},
		Reason: "customer_request",
	})
	if err != nil {
		t.Fatalf("RefundPayment returned error: %v", err)
	}
	if got.Status != "refunded" {
		t.Errorf("expected status refunded, got %q", got.Status)
	}
	if capturedBody["reason"] != "customer_request" {
		t.Errorf("expected reason in body, got %v", capturedBody["reason"])
	}
}

func TestIdempotencyKeyAutoGenerated(t *testing.T) {
	var capturedKey string

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		capturedKey = r.Header.Get("Idempotency-Key")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(Payment{PaymentID: "pay_auto", Status: "pending"})
	})

	_, err := client.CreatePayment(context.Background(), CreatePaymentRequest{
		Amount:  Money{Amount: "100.00", Currency: "UZS"},
		OrderID: "order_idem",
		// IdempotencyKey intentionally not set
	})
	if err != nil {
		t.Fatalf("CreatePayment error: %v", err)
	}
	if capturedKey == "" {
		t.Fatal("expected Idempotency-Key header to be auto-generated, got empty string")
	}
}

func TestIdempotencyKeyExplicit(t *testing.T) {
	const explicitKey = "my-explicit-key-123"
	var capturedKey string

	_, client := newTestServerFn(t, func(w http.ResponseWriter, r *http.Request) {
		capturedKey = r.Header.Get("Idempotency-Key")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(Payment{PaymentID: "pay_explicit", Status: "pending"})
	})

	_, err := client.CreatePayment(context.Background(), CreatePaymentRequest{
		Amount:         Money{Amount: "100.00", Currency: "UZS"},
		OrderID:        "order_explicit",
		IdempotencyKey: explicitKey,
	})
	if err != nil {
		t.Fatalf("CreatePayment error: %v", err)
	}
	if capturedKey != explicitKey {
		t.Errorf("expected Idempotency-Key %q, got %q", explicitKey, capturedKey)
	}
}

func TestListPayments_success(t *testing.T) {
	want := []*Payment{
		{PaymentID: "pay_1", Status: "captured"},
		{PaymentID: "pay_2", Status: "authorized"},
	}

	_, client := newTestServer(t, http.StatusOK, map[string]any{"payments": want})

	got, err := client.ListPayments(context.Background(), ListPaymentsParams{PageSize: 10})
	if err != nil {
		t.Fatalf("ListPayments error: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("expected 2 payments, got %d", len(got))
	}
	if got[0].PaymentID != "pay_1" {
		t.Errorf("expected pay_1, got %q", got[0].PaymentID)
	}
}

func TestAPIError_serverError(t *testing.T) {
	_, client := newTestServer(t, http.StatusInternalServerError, map[string]string{
		"message": "internal server error",
	})

	_, err := client.GetPayment(context.Background(), "pay_xyz")

	apiErr, ok := err.(*Error)
	if !ok {
		t.Fatalf("expected *Error, got: %T %v", err, err)
	}
	if apiErr.StatusCode != 500 {
		t.Errorf("expected StatusCode 500, got %d", apiErr.StatusCode)
	}
}
